<a href="https://colab.research.google.com/github/shabeelsairat/data-science-projects/blob/main/(ETL)Perfume_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Extracting the Dataset**

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kanchana1990/perfume-e-commerce-dataset-2024")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'perfume-e-commerce-dataset-2024' dataset.
Path to dataset files: /kaggle/input/perfume-e-commerce-dataset-2024

In [3]:
import os

# The 'path' variable returned by kagglehub.dataset_download
# already points to the directory where the dataset files are located.
# This means the dataset is already "extracted" by kagglehub.dataset_download.
# Therefore, the zipfile extraction step is not needed.
extract_dir = path # Use the path directly as the extraction directory

# Optionally, you can list the contents to confirm the files are there
print("Dataset files are located at:", extract_dir)
print("Contents of the dataset directory:")
for item in os.listdir(extract_dir):
    print(item)

Dataset files are located at: /kaggle/input/perfume-e-commerce-dataset-2024
Contents of the dataset directory:
ebay_womens_perfume.csv
ebay_mens_perfume.csv

In [4]:
import pandas as pd
import os

file_name = "ebay_womens_perfume.csv"
file_path = os.path.join(extract_dir, file_name)

rawdata = pd.read_csv(file_path)

In [5]:
rawdata.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

In [6]:
df = rawdata.copy()

In [7]:
df.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

In [8]:
df.describe()

             price   available          sold
count  1000.000000  869.000000    984.000000
mean     39.892980   21.426928    497.321138
std      29.072186   51.476703   1372.510561
min       1.990000    2.000000      1.000000
25%      20.700000    6.000000     15.000000
50%      32.990000   10.000000     52.000000
75%      49.990000   10.000000    263.750000
max     299.990000  557.000000  17854.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               998 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          869 non-null    float64
 6   availableText      992 non-null    object
 7   sold               984 non-null    float64
 8   lastUpdated        927 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB

##**Transforming the Dataset**

fixing the duplicate values if exists

In [10]:
print(df[df.duplicated()])

      brand                                              title     type  \
662  FLOWER  12 Piece Woman’s Perfume Lot: Assorted scents ...  Perfume

     price priceWithCurrency  available         availableText  sold  \
662   48.0         US $48.00        4.0  4 available / 1 sold   1.0

    lastUpdated                     itemLocation
662         NaN  Webster, Florida, United States

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.duplicated().any())

False

Now working with null values

In [13]:
df.isna().sum()

brand                  1
title                  0
type                   2
price                  0
priceWithCurrency      0
available            131
availableText          8
sold                  16
lastUpdated           72
itemLocation           0
dtype: int64

In [14]:
df['brand'].value_counts()

brand
Lancôme                      37
Versace                      33
Dolce&Gabbana                30
Jo Malone                    29
Carolina Herrera             27
                             ..
DKNY                          1
United Colors of Benetton     1
Maison                        1
Vince Camuto                  1
Juliette Has A Gun            1
Name: count, Length: 247, dtype: int64

In [15]:
df[df['brand'].isnull()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
856,NaN,Bright Crystal de Versace Eau de Toilette 3.0 ...,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos"

In [16]:
df.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

##Filling some of the null values

In [17]:
values_to_fill = {
    'brand': 'Versace',
    'type': 'Eau de Toilette',
    'available': 2,
    'sold': 3
}

# Fill all nulls in row 1 at once
for col, value in values_to_fill.items():
    df.loc[856, col] = value

In [18]:
df.loc[856]

brand                                                          Versace
title                Bright Crystal de Versace Eau de Toilette 3.0 ...
type                                                   Eau de Toilette
price                                                            29.99
priceWithCurrency                                            US $29.99
available                                                          2.0
availableText                               2 disponibles / 3 vendidos
sold                                                               3.0
lastUpdated                                   23 may 2024 02:42:14 EST
itemLocation                       Hamtramck, Michigan, Estados Unidos
Name: 856, dtype: object

In [19]:
df[df['type'].isnull()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
463,As Show,Carmina By Creed EDP 75ml 2.5 oz Spray For Wom...,NaN,128.88,US $128.88,10.0,10 available / 21 sold,21.0,"May 24, 2024 00:32:16 PDT","New Jersey, United States, Hong Kong"

In [20]:
df.loc[463, 'type'] = 'Eau de Parfum'

In [21]:
df.isna().sum()

brand                  0
title                  0
type                   0
price                  0
priceWithCurrency      0
available            130
availableText          8
sold                  15
lastUpdated           72
itemLocation           0
dtype: int64

In [22]:
df[df['available'].isnull()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
6,AS SHOW,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,58.99,US $58.99,NaN,Out of Stock / 18 sold,18.0,"May 24, 2024 00:15:13 PDT","Astoria, New York, United States"
8,Versace,Versace Bright Crystal by Versace for Women ED...,Eau de Toilette,29.99,US $29.99,NaN,Last One / 251 sold,251.0,"May 23, 2024 22:39:02 PDT","Jamaica, New York, United States"
18,AS SHOWN,PRADA Paradoxe By Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,NaN,Last One / 43 sold,43.0,"May 23, 2024 01:10:19 PDT","New York, New York, United States"
23,YSL,Libre by Yves Saint Laurent YSL 3 oz EDP Perfu...,Eau de Parfum,54.95,US $54.95,NaN,Last One / 25 sold,25.0,"May 24, 2024 00:08:02 PDT","Stuyvesant Falls, New York, United States"
27,Dolce&Gabbana,Dolce & Gabbana Light Blue 6.7 oz Spray Eau De...,Eau de Toilette,53.99,US $53.99,NaN,Out of Stock / 54 sold,54.0,"May 24, 2024 03:14:29 PDT","Ecorse, Michigan, United States"
...,...,...,...,...,...,...,...,...,...,...
975,Gucci,Gucci Guilty 1.7 oz EDT Perfume for Women New ...,Eau de Toilette,64.58,US $64.58,NaN,Limited quantity available / 275 sold,275.0,"May 21, 2024 15:16:00 PDT","Hackensack, New Jersey, United States"
982,As Show,Carmina By Creed2.5 oz / 75 ml Eau De Parfum F...,Eau de Parfum/Perfume,124.99,US $124.99,NaN,Last One / 3 sold,3.0,"May 24, 2024 00:32:54 PDT","USA, New Jersey, Hong Kong"
983,Burberry,Burberry Her ELIXIR DE PARFUM EDP Intense-Delu...,Eau de Parfum,13.00,US $13.00,NaN,NaN,NaN,NaN,"Chino, California, United States"
990,United Colors of Benetton,United Colors of Benetton MINI COLORS FEMME WO...,Eau de Toilette,24.99,US $24.99,NaN,4 lots available (8 items per lot) / 79 sold,79.0,"Mar 26, 2024 11:45:52 PDT","Brooklyn, New York, United States"
991,Maison,Maison Louis Marie No.04 Bois de Balincourt Pe...,Perfume,22.09,US $22.09,NaN,Last One / 41 sold,41.0,"May 22, 2024 12:50:46 PDT","Lodi, California, United States"

In [23]:
df.loc[
    df['available'].isna() &
    df['availableText'].str.contains(r'Out of Stock', na=False),
    'available'
] = 0


# fill available = 1 when Last One
df.loc[
    df['available'].isna() &
    df['availableText'].str.contains(r'Last One', na=False),
    'available'
] = 1

In [24]:
df.isna().sum()

brand                 0
title                 0
type                  0
price                 0
priceWithCurrency     0
available            55
availableText         8
sold                 15
lastUpdated          72
itemLocation          0
dtype: int64

In [25]:
# drop rows where all three columns are null
df = df.dropna(subset=['available', 'availableText', 'sold'], how='all')

In [26]:
df.isna().sum()

brand                 0
title                 0
type                  0
price                 0
priceWithCurrency     0
available            47
availableText         0
sold                  7
lastUpdated          64
itemLocation          0
dtype: int64

In [27]:
df.loc[358, 'available'] = 30
df.loc[688, 'available'] = 30
df.loc[990, 'available'] = 32

fixing the timestamp as well as extracting date, month and hour for further analysis

In [28]:
df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], utc=True, errors='coerce')

/tmp/ipykernel_2970/2291615447.py:1: FutureWarning: Parsed string "May 23, 2024 10:43:50 PDT" included an un-recognized timezone "PDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], utc=True, errors='coerce')

In [29]:
df['update_date'] = df['lastUpdated'].dt.date
df['update_month'] = df['lastUpdated'].dt.month
df['update_hour'] = df['lastUpdated'].dt.hour

In [30]:
df.isna().sum()

brand                  0
title                  0
type                   0
price                  0
priceWithCurrency      0
available             44
availableText          0
sold                   7
lastUpdated          146
itemLocation           0
update_date          146
update_month         146
update_hour          146
dtype: int64

Now time to do some advanced cleaning

In [31]:
df[df['update_date'].isnull()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,update_date,update_month,update_hour
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaT,"Little Ferry, New Jersey, United States",NaT,NaN,NaN
19,Dolce & Gabbana,D&G DOLCE & GABBANA LIGHT BLUE EAU INTENSE WOM...,Eau de Parfum,11.00,US $11.00,10.0,"More than 10 available / 1,613 sold",1613.0,NaT,"Albany, New York, United States",NaT,NaN,NaN
20,QRC,Oxytocin-N 15iu Per Spray 1oz (30ml),Spray,27.00,US $27.00/ea,10.0,More than 10 available / 218 sold,218.0,NaT,"Oklahoma City, Oklahoma, United States",NaT,NaN,NaN
21,~ CREPE ERASE ~,CREPE ERASE-BODY FIRM ADVANCED BODY REPAIR TRE...,~ BODY FIRM ADVANCED BODY REPAIR TREATMENT ~,29.99,US $29.99,10.0,More than 10 available / 1 sold,1.0,NaT,"Melrose Park, Illinois, United States",NaT,NaN,NaN
36,Parfums de Marly,PDM PARFUMS DE MARLY DELINA EXCLUSIF 1.5ml .05...,Parfum,12.00,US $12.00,10.0,More than 10 available / 59 sold,59.0,NaT,"Albany, New York, United States",NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,Parfums de Marly,Parfums de Marly Delina 2.5 fl oz Women's EDP ...,Eau de Parfum,80.00,US $80.00,10.0,More than 10 available / 2 sold,2.0,NaT,"Pittsburgh, Pennsylvania, United States",NaT,NaN,NaN
978,Tom Ford,Tom Ford Black Orchid Eau De Parfum Sample Siz...,Eau de Parfum,11.49,US $11.49,10.0,More than 10 available / 64 sold,64.0,NaT,"Burlington, Iowa, United States",NaT,NaN,NaN
989,DKNY,Be Extra Delicious By DKNY 0.24oz EDP Women's ...,Eau de Parfum,14.95,US $14.95,19.0,19 available / 5 sold,5.0,NaT,"Fort Lauderdale, Florida, United States",NaT,NaN,NaN
990,United Colors of Benetton,United Colors of Benetton MINI COLORS FEMME WO...,Eau de Toilette,24.99,US $24.99,32.0,4 lots available (8 items per lot) / 79 sold,79.0,NaT,"Brooklyn, New York, United States",NaT,NaN,NaN
992,Calvin Klein,Obsession Perfume by Calvin Klein - 3.3 / 3.4 ...,Eau de Parfum,24.65,US $24.65,10.0,More than 10 available / 615 sold,615.0,NaT,"Poway, California, United States",NaT,NaN,NaN

In [32]:
df['type'].unique()

array(['Eau de Parfum', 'Eau de Toilette', 'Eau De Parfum', 'Spray',
       '~ BODY FIRM ADVANCED BODY REPAIR TREATMENT ~', 'Parfum',
       'Fragrance Mist', 'Deodorant Stick', 'Gift Sets', 'Eau de Perfume',
       'Eau de Cologne', '3 Pc', 'Eau de Parfum, Eau De Parfume',
       'Body Spray', 'Extrait de Parfum', 'Mist',
       'Eau de Toilette, Spray', 'Perfume', '/', 'Perfume, Eau de Parfum',
       'Fragrances', 'Eau De Cologne', 'Hair Perfume',
       'Eau de Parfum, Spray', 'Cream', 'Eau De Parfum 2 Pcs Set', 'EDT',
       "L'Eau de Parfum", 'Eau de Parfume', "L'eau de Parfum",
       'SKIN_MOISTURIZER', 'EDP and Parfum', 'Fine Fragrance Mist',
       'Lotion', 'Does not apply', 'Scented Oils', 'Shimmer', 'EDP',
       'Eau De Toilette', 'Perfume Fragrance Mist', 'Perfume Oil',
       'Parfum, Lotion, Gloss and Blush', 'Bath Oil', 'Elixir De Parfum',
       'Body Mist', 'ASST', 'BEAUTY', 'Extract Parfum', 'Does Not Apply',
       'Shimmering Body Oil', 'Body Powder', 'Eau De Parfum Supreme',
       'cologne', 'Perfume Gift Sets', 'Toilette Spray',
       'Eau De Parfum Spray (Unisex Tester) 3.4 oz', 'Body Lotion',
       'deodorant', 'Esprit de Parfum', 'SOLID PERFUME STICK', 'Cologne',
       'Eau De Toilette Spray 3.4 oz', 'Eau De Parfum 3 Pcs Set',
       'Sensuous Body Moisturizer', 'Cologne Spray', 'Pink Sugar',
       'Oil Perfume', 'FRAGRANCE BODY MIST', 'Eau de Parfum/Perfume', '1'],
      dtype=object)

As we can see here that, there are many unnecesary extra types which are needed to be organized.

In [33]:
df['type'] = df['type'].str.lower().str.strip()

In [34]:
df['type'].value_counts()

type
eau de parfum            575
eau de toilette          191
perfume                   53
eau de cologne            38
eau de perfume            23
                        ...
pink sugar                 1
oil perfume                1
fragrance body mist        1
eau de parfum/perfume      1
1                          1
Name: count, Length: 64, dtype: int64

In [47]:
import numpy as np
conditions = [
    df['type'].str.contains(r'edp|eau de parfum|parfum|elixir', na=False),
    df['type'].str.contains(r'edt|eau de toilette|toilette', na=False),
    df['type'].str.contains(r'cologne', na=False),
    df['type'].str.contains(r'mist', na=False),
    df['type'].str.contains(r'deodorant', na=False),
]

choices = [
    'Eau de Parfum',
    'Eau de Toilette',
    'Cologne',
    'Mist',
    'Deodorant'
]

df['type_clean'] = np.select(conditions, choices, default='Other')

In [48]:
df['type_clean'].value_counts()

type_clean
Eau de Parfum      601
Eau de Toilette    200
Other              130
Cologne             42
Mist                16
Deodorant            2
Name: count, dtype: int64

In [57]:
df[df['type_clean'] == 'Other'].head(20)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,update_date,update_month,update_hour,type_clean
20,QRC,Oxytocin-N 15iu Per Spray 1oz (30ml),spray,27.00,US $27.00/ea,10.0,More than 10 available / 218 sold,218.0,NaT,"Oklahoma City, Oklahoma, United States",NaT,NaN,NaN,Other
21,~ CREPE ERASE ~,CREPE ERASE-BODY FIRM ADVANCED BODY REPAIR TRE...,~ body firm advanced body repair treatment ~,29.99,US $29.99,10.0,More than 10 available / 1 sold,1.0,NaT,"Melrose Park, Illinois, United States",NaT,NaN,NaN,Other
63,Donna Karan,"Be Delicious DKNY by Donna Karan, 8 oz Fragran...",gift sets,16.26,US $16.26/ea,10.0,More than 10 available / 110 sold,110.0,2024-05-24 10:21:10+00:00,"Edison, New Jersey, United States",2024-05-24,5.0,10.0,Other
68,Juicy Couture,VIVA LA JUICY GOLD COUTURE by Juicy Couture Wo...,eau de perfume,36.79,US $36.79/ea,68.0,"68 available / 1,498 sold",1498.0,2024-05-24 09:05:08+00:00,"Dallas, Texas, United States",2024-05-24,5.0,9.0,Other
74,Elizabeth Arden,Elizabeth Arden White Tea Fragrance Collection...,3 pc,19.45,US $19.45,50.0,50 available / 2 sold,2.0,2024-05-24 07:12:19+00:00,"Ronkonkoma, New York, United States",2024-05-24,5.0,7.0,Other
76,Sol De Janeiro,After Hours by Sol de Janeiro 3OZ/90 ML Fragra...,body spray,20.49,US $20.49/ea,8.0,8 available / 190 sold,190.0,2024-05-23 18:04:39+00:00,"Dayton,New Jersey, Hong Kong",2024-05-23,5.0,18.0,Other
85,Kim Kardashian,KIM KARDASHIAN GOLD Perfume 3.3 / 3.4 oz EDP F...,eau de perfume,16.63,US $16.63/ea,37.0,37 available / 528 sold,528.0,2024-05-14 12:55:23+00:00,"Dallas, Texas, United States",2024-05-14,5.0,12.0,Other
98,Clinique,Clinique Happy by Clinique 3.3 / 3.4 oz Perfum...,perfume,21.27,US $21.27,2.0,2 available / 61 sold,61.0,2024-05-09 20:50:21+00:00,"CA, United States",2024-05-09,5.0,20.0,Other
99,Unbranded,Yara by Lattafa Perfumes | Eau De Parfum-100ml...,/,15.89,US $15.89,10.0,More than 10 available / 434 sold,434.0,2024-05-24 06:56:49+00:00,"shanghai, China",2024-05-24,5.0,6.0,Other
100,Valentino,Valentine Milano For Women Perfume 3.4 fl.oz f...,perfume,10.99,US $10.99/ea,10.0,More than 10 available / 94 sold,94.0,2024-05-08 15:45:55+00:00,"Katy, Texas, United States",2024-05-08,5.0,15.0,Other
106,Alfred Sung,SHI by Alfred Sung Perfume for Women EDP 3.3 /...,eau de perfume,20.45,US $20.45/ea,110.0,"110 available / 4,308 sold",4308.0,2024-05-24 10:02:06+00:00,"Dallas, Texas, United States",2024-05-24,5.0,10.0,Other
132,Al Haramain,Al Haramain Amber Oud White Edition EDP 3.4 oz...,fragrances,36.65,US $36.65,3.0,3 available / 22 sold,22.0,2024-05-23 14:21:07+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,14.0,Other
150,Unbranded,SOL DE JANEIRO Brazilian Crush 39 Perfume Body...,perfume,19.75,US $19.75,10.0,More than 10 available / 33 sold,33.0,2024-05-19 17:30:18+00:00,"California,United States,HK, Hong Kong",2024-05-19,5.0,17.0,Other
154,Aquolina,Pink Sugar hair perfume by Aquolina for women ...,hair perfume,12.36,US $12.36/ea,417.0,"417 available / 1,130 sold",1130.0,2024-05-12 23:45:01+00:00,"Dallas, Texas, United States",2024-05-12,5.0,23.0,Other
165,Armaf,Club de Nuit by Armaf perfume for women EDP 6....,eau de perfume,36.59,US $36.59/ea,175.0,175 available / 931 sold,931.0,2024-05-24 10:59:09+00:00,"Dallas, Texas, United States",2024-05-24,5.0,10.0,Other
174,Donna Karan,Donna karen Cashmere Mist Deodorant 1.7oz,cream,26.99,US $26.99,10.0,More than 10 available / 69 sold,69.0,NaT,"Chicago, Illinois, United States",NaT,NaN,NaN,Other
176,Katy Perry,MEOW by KATY PERRY Eau de Parfum 3.4 oz for 3....,eau de perfume,23.75,US $23.75/ea,132.0,132 available / 417 sold,417.0,2024-05-23 01:01:37+00:00,"Dallas, Texas, United States",2024-05-23,5.0,1.0,Other
178,Clinique,Aromatics Elixir by Clinique 3.4 oz/100 ml Per...,perfume,33.00,US $33.00/ea,10.0,10 available / 232 sold,232.0,2024-05-23 16:54:40+00:00,"Katy, Texas, United States",2024-05-23,5.0,16.0,Other
198,Philosophy,NIB Philosophy Pure Grace 2oz EDT Women's Per...,perfume,30.17,US $30.17,10.0,More than 10 available / 441 sold,441.0,2024-05-21 18:30:00+00:00,"Alexandria, Minnesota, United States",2024-05-21,5.0,18.0,Other
200,Maison Alhambra,Maison Alhambra Ladies La Vita Bella Intensa E...,fragrances,18.79,US $18.79,3.0,3 available / 22 sold,22.0,2024-05-23 09:57:03+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,9.0,Other

found some of the perfumes that are EDP but still existing inside others category

In [66]:
conditions = [
    df['type'].str.contains(r'edp|eau de parfum|eau de perfume|parfum|perfume|elixir', na=False),
    df['type'].str.contains(r'edt|eau de toilette|toilette', na=False),
    df['type'].str.contains(r'cologne', na=False),
    df['type'].str.contains(r'mist', na=False),
    df['type'].str.contains(r'deodorant', na=False),
    df['type'].str.contains(r'spray|body spray', na=False),
    df['type'].str.contains(r'cream|lotion', na=False),
    df['title'].str.contains(r'cream|lotion', na=False)
]

choices = [
    'Eau de Parfum',
    'Eau de Toilette',
    'Cologne',
    'Mist',
    'Deodorant',
    'Body Spray',
    'Skin Product'
]

df['type_clean'] = np.select(conditions, choices, default='Other')

In [67]:
df[df['type_clean'] == 'Other'].head(20)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,update_date,update_month,update_hour,type_clean
21,~ CREPE ERASE ~,CREPE ERASE-BODY FIRM ADVANCED BODY REPAIR TRE...,~ body firm advanced body repair treatment ~,29.99,US $29.99,10.0,More than 10 available / 1 sold,1.0,NaT,"Melrose Park, Illinois, United States",NaT,NaN,NaN,Other
63,Donna Karan,"Be Delicious DKNY by Donna Karan, 8 oz Fragran...",gift sets,16.26,US $16.26/ea,10.0,More than 10 available / 110 sold,110.0,2024-05-24 10:21:10+00:00,"Edison, New Jersey, United States",2024-05-24,5.0,10.0,Other
74,Elizabeth Arden,Elizabeth Arden White Tea Fragrance Collection...,3 pc,19.45,US $19.45,50.0,50 available / 2 sold,2.0,2024-05-24 07:12:19+00:00,"Ronkonkoma, New York, United States",2024-05-24,5.0,7.0,Other
99,Unbranded,Yara by Lattafa Perfumes | Eau De Parfum-100ml...,/,15.89,US $15.89,10.0,More than 10 available / 434 sold,434.0,2024-05-24 06:56:49+00:00,"shanghai, China",2024-05-24,5.0,6.0,Other
132,Al Haramain,Al Haramain Amber Oud White Edition EDP 3.4 oz...,fragrances,36.65,US $36.65,3.0,3 available / 22 sold,22.0,2024-05-23 14:21:07+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,14.0,Other
200,Maison Alhambra,Maison Alhambra Ladies La Vita Bella Intensa E...,fragrances,18.79,US $18.79,3.0,3 available / 22 sold,22.0,2024-05-23 09:57:03+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,9.0,Other
277,Clinique,NEW Aromatics Elixir By Clinique For Women. Bo...,skin_moisturizer,20.79,US $20.79,7.0,7 available / 33 sold,33.0,2024-05-19 13:44:31+00:00,"Plainfield, Illinois, United States",2024-05-19,5.0,13.0,Other
377,Kate Spade New York,In Full Bloom Blush by Kate Spade for Women - ...,does not apply,14.40,US $14.40,5.0,5 available / 73 sold,73.0,2024-05-22 21:21:54+00:00,"Old Bethpage, New York, United States",2024-05-22,5.0,21.0,Other
382,Spiritual Sky,(2-Pack) Patchouly Musk Scented Oil - Spiritua...,scented oils,12.99,US $12.99/ea,10.0,More than 10 available / 49 sold,49.0,2024-05-24 04:28:37+00:00,"Miami, Florida, United States",2024-05-24,5.0,4.0,Other
385,Tom Ford,"Tom Ford Soleil Neige Sheer Body Oil, Full Siz...",shimmer,25.00,US $25.00,5.0,5 available / 79 sold,79.0,2024-05-21 09:19:12+00:00,"Camarillo, California, United States",2024-05-21,5.0,9.0,Other
404,Lattafa,Lattafa Ladies Haya EDP 3.4 oz Fragrances 6291...,fragrances,34.77,US $34.77,3.0,3 available / 9 sold,9.0,2024-05-23 08:44:45+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,8.0,Other
468,Versace,"Versace by Versace, 5 Piece Variety Mini Gift ...",gift sets,43.15,US $43.15/ea,10.0,More than 10 available / 66 sold,66.0,2024-05-23 12:37:45+00:00,"Edison, New Jersey, United States",2024-05-23,5.0,12.0,Other
476,Estée Lauder,Youth Dew by Estee Lauder for Women Bath Oil 2...,bath oil,40.00,US $40.00,10.0,More than 10 available / 10 sold,10.0,NaT,"Boiling Springs, Pennsylvania, United States",NaT,NaN,NaN,Other
480,Sarah Jessica Parker,Sarah Jessica Parker Ladies Lovely EDP Spray 6...,fragrances,27.25,US $27.25,3.0,3 available / 9 sold,9.0,2024-05-23 17:56:48+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,17.0,Other
486,Clinique,Aromatics Elixir By Clinique For Women. Body S...,skin_moisturizer,23.00,US $23.00,1.0,Last One / 102 sold,102.0,2024-05-23 09:53:48+00:00,"Edison, New Jersey, United States",2024-05-23,5.0,9.0,Other
493,Jimmy Choo,Jimmy Choo Mini Set Gift Set Fragrances 338646...,fragrances,45.11,US $45.11,3.0,3 available / 15 sold,15.0,2024-05-23 05:10:19+00:00,"Brooklyn, New York, United States",2024-05-23,5.0,5.0,Other
562,ASST,MOTHER'S DAY SALE DG YSL GUESS KENZO BURBERRY...,asst,13.37,US $13.37,92.0,92 available / 7 sold,7.0,NaT,"Henderson, Nevada, United States",NaT,NaN,NaN,Other
565,Al-Rehab,Soft - Al-Rehab Eau De Natural Perfume Spray -...,beauty,9.25,US $9.25,10.0,More than 10 available / 30 sold,30.0,NaT,"Princeton, New Jersey, United States",NaT,NaN,NaN,Other
574,Cacharel,Noa by Cacharel for Women Eau de Toilette Spra...,does not apply,20.00,US $20.00/ea,10.0,More than 10 available / 79 sold,79.0,NaT,"New York, New York, United States",NaT,NaN,NaN,Other
594,Tom Ford,TOM FORD SOLEIL BLANC SHIMMERING BODY OIL GOLD...,shimmering body oil,34.99,US $34.99/ea,9.0,9 available / 30 sold,30.0,NaT,"East Brunswick, New Jersey, United States",NaT,NaN,NaN,Other

Need to work with "title" column as it holds extra infos about perfume types

In [68]:
df['title'] = df['title'].str.lower().str.strip()

In [82]:
# create mask for problematic rows
mask = df['type_clean'] == 'Other'

# fix using title column

# Eau de Parfum
df.loc[
    mask & df['title'].str.contains(r'edp|eau de parfum|parfum|soft - al-rehab eau de natural perfume spray', case=False, na=False),
    'type_clean'
] = 'Eau de Parfum'

# Eau de Toilette
df.loc[
    mask & df['title'].str.contains(r'edt|eau de toilette', case=False, na=False),
    'type_clean'
] = 'Eau de Toilette'

# Cologne
df.loc[
    mask & df['title'].str.contains(r'cologne', case=False, na=False),
    'type_clean'
] = 'Cologne'

# Mist
df.loc[
    mask & df['title'].str.contains(r'mist', case=False, na=False),
    'type_clean'
] = 'Mist'

# Deodorant
df.loc[
    mask & df['title'].str.contains(r'deodorant', case=False, na=False),
    'type_clean'
] = 'Deodorant'

In [98]:
df['type_clean'].value_counts()

type_clean
Eau de Parfum      701
Eau de Toilette    202
Cologne             42
Other               16
Mist                16
Body Spray           6
Skin Product         6
Deodorant            2
Name: count, dtype: int64

In [99]:
# drop old column
df = df.drop(columns=['type'])

# rename new cleaned column
df = df.rename(columns={'type_clean': 'type'})

In [100]:
df.head()

,brand,title,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,update_date,update_month,update_hour,type
0,Carolina Herrera,good girl by carolina herrera 2.7 oz eau de pa...,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,2024-05-23 10:43:50+00:00,"Thomasville, Alabama, United States",2024-05-23,5.0,10.0,Eau de Parfum
1,As Shown,parfums de marly delina la rosee eau de parfum...,79.99,US $79.99,5.0,5 available / 40 sold,40.0,2024-05-24 00:15:48+00:00,"New Jersey, Hong Kong",2024-05-24,5.0,0.0,Eau de Parfum
2,PRADA,prada paradoxe by prada edp 3.0oz/90ml spray p...,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,2024-05-14 20:54:25+00:00,"Orange, New Jersey, United States",2024-05-14,5.0,20.0,Eau de Parfum
3,As Show,j'adore parfum d'eau by christian 3.4 oz edp f...,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,2024-05-23 01:23:05+00:00,"USA, New Jersey, Hong Kong",2024-05-23,5.0,1.0,Eau de Parfum
4,Khadlaj,shiyaaka for men edp spray 100ml (3.4 fl.oz) b...,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaT,"Little Ferry, New Jersey, United States",NaT,NaN,NaN,Eau de Parfum

In [102]:
df['priceWithCurrency'].unique()

array(['US $43.99/ea', 'US $79.99', 'US $59.99', 'US $59.99/ea',
       'US $29.99/ea', 'US $51.99/ea', 'US $58.99', 'US $52.79/ea',
       'US $29.99', 'US $22.75/ea', 'US $39.99/ea', 'US $64.99/ea',
       'US $60.99/ea', 'US $43.49/ea', 'US $29.20/ea', 'US $13.00',
       'US $39.69/ea', 'US $11.00', 'US $27.00/ea', 'US $16.27/ea',
       'US $54.95', 'US $49.99/ea', 'US $84.99', 'US $53.99', 'US $99.99',
       'US $40.92/ea', 'US $22.90/ea', 'US $42.00/ea', 'US $44.88/ea',
       'US $66.99', 'US $129.99', 'US $22.99', 'US $12.00', 'US $32.95',
       'US $31.05/ea', 'US $32.20/ea', 'US $17.90/ea', 'US $29.75',
       'US $19.99/ea', 'US $42.88', 'US $100.99', 'US $26.05/ea',
       'US $54.99/ea', 'US $47.49/ea', 'US $43.99', 'US $32.00',
       'US $31.50/ea', 'US $42.99/ea', 'US $98.99', 'US $39.99',
       'US $27.99/ea', 'US $15.49/ea', 'US $23.25/ea', 'US $16.26/ea',
       'US $49.68/ea', 'US $27.90/ea', 'US $36.79/ea', 'US $48.88',
       'US $55.99/ea', 'US $42.98', 'US $15.98/ea', 'US $19.45',
       'US $20.49/ea', 'US $31.00/ea', 'US $24.99/ea', 'US $19.00/ea',
       'US $14.00', 'US $34.00', 'US $49.00', 'US $30.99/ea',
       'US $16.63/ea', 'US $60.00', 'US $42.99', 'US $19.00',
       'US $25.27/ea', 'US $29.90/ea', 'US $20.93/ea', 'US $30.98',
       'US $41.50/ea', 'US $30.79', 'US $21.27', 'US $15.89',
       'US $10.99/ea', 'US $37.88/ea', 'US $30.95/ea', 'US $25.23/ea',
       'US $23.88/ea', 'US $18.50', 'US $20.45/ea', 'US $12.78/ea',
       'US $33.99', 'US $14.75/ea', 'US $33.52/ea', 'US $28.00/ea',
       'US $9.70', 'US $44.99', 'US $33.80/ea', 'US $22.99/ea',
       'US $49.99', 'US $17.89/ea', 'US $35.09/ea', 'US $25.57/ea',
       'US $16.44/ea', 'US $7.99/ea', 'US $36.65', 'US $54.99',
       'US $12.49/ea', 'US $9.25/ea', 'US $50.68/ea', 'US $42.00',
       'US $38.92/ea', 'US $33.38/ea', 'US $29.65', 'US $18.63/ea',
       'US $28.05/ea', 'US $55.10', 'US $99.99/ea', 'US $19.75',
       'US $34.08/ea', 'US $12.95/ea', 'US $30.00', 'US $12.36/ea',
       'US $43.69/ea', 'US $35.39/ea', 'US $34.28/ea', 'US $43.32/ea',
       'US $41.99', 'US $29.49/ea', 'US $41.99/ea', 'US $36.59/ea',
       'US $33.99/ea', 'US $49.00/ea', 'US $119.99/ea', 'US $26.99/ea',
       'US $15.99/ea', 'US $19.68', 'US $42.28', 'US $26.99',
       'US $109.95/ea', 'US $23.75/ea', 'US $18.99/ea', 'US $33.00/ea',
       'US $41.49', 'US $32.12', 'US $55.39', 'US $36.99', 'US $28.99/ea',
       'US $34.59', 'US $39.47', 'US $29.90', 'US $20.42/ea',
       'US $25.42/ea', 'US $62.99/ea', 'US $35.08/ea', 'US $95.99',
       'US $30.17', 'US $37.19/ea', 'US $18.79', 'US $40.00/ea',
       'US $20.44/ea', 'US $44.99/ea', 'US $14.89', 'US $23.95/ea',
       'US $52.78', 'US $54.90', 'US $43.33/ea', 'US $29.45/ea',
       'US $20.00/ea', 'US $20.48/ea', 'US $22.09', 'US $34.38/ea',
       'US $24.24/ea', 'US $21.95/ea', 'US $39.89/ea', 'US $18.94/ea',
       'US $24.51', 'US $32.99/ea', 'US $16.95', 'US $35.73/ea',
       'US $34.98/ea', 'US $59.96', 'US $64.88/ea', 'US $69.99/ea',
       'US $25.69/ea', 'US $49.68', 'US $33.92', 'US $34.99/ea',
       'US $30.45/ea', 'US $67.50', 'US $5.99', 'US $15.00/ea',
       'US $15.99', 'US $79.72/ea', 'US $39.98', 'US $44.95', 'US $60.37',
       'US $53.99/ea', 'US $23.90', 'US $26.43/ea', 'US $29.95/ea',
       'US $15.52/ea', 'US $45.99', 'US $27.31', 'US $38.99/ea',
       'US $45.92/ea', 'US $12.99', 'US $58.61/ea', 'US $86.99/ea',
       'US $54.00', 'US $5.99/ea', 'US $24.39/ea', 'US $21.98',
       'US $76.99/ea', 'US $33.89/ea', 'US $8.99', 'US $18.95/ea',
       'US $20.79', 'US $89.99/ea', 'US $20.31/ea', 'US $34.60/ea',
       'US $38.14/ea', 'US $16.89/ea', 'US $49.81', 'US $29.95',
       'US $85.56/ea', 'US $119.00', 'US $27.26/ea', 'US $48.99/ea',
       'US $28.99', 'US $37.99', 'US $20.99', 'US $86.99', 'US $29.55/ea',
       'US $9.99', 'US $26.90/ea', 'US $44.78', 'US $14.50', 'US $14.95',
       'US $28.15', 'US $14.74/ea', 'US $35.99/ea', 'US $19.05',
       'US $29.54/ea', 'US $47.80/ea', 'US $13.95/ea', 'US $43.00',
       'US $22.51/ea', 'US $9.92', 'US $47.65/ea', 'US $41.58/ea',
       'US $16.87/ea', 'US $59.40/ea', 'US $12.99/ea', 'US $11.66/ea',
       'US $43.15/ea', 'US $15.80/ea', 'US $15.00', 'US $17.52/ea',
       'US $19.83/ea', 'US $17.49/ea', 'US $19.12/ea', 'US $30.90',
       'US $13.89', 'US $12.74', 'US $48.00', 'US $26.66/ea',
       'US $33.34/ea', 'US $12.00/ea', 'US $17.57/ea', 'US $20.00',
       'US $38.68/ea', 'US $14.45/ea', 'US $15.88', 'US $32.13/ea',
       'US $9.95/ea', 'US $25.25/ea', 'US $22.25/ea', 'US $21.99/ea',
       'US $63.99', 'US $39.95', 'US $15.77/ea', 'US $17.00', 'US $24.50',
       'US $14.40', 'US $69.99', 'US $63.00', 'US $25.99', 'US $23.99',
       'US $25.00', 'US $15.42/ea', 'US $28.89/ea', 'US $33.59/ea',
       'US $64.99', 'US $11.88', 'US $25.66/ea', 'US $52.99',
       'US $26.35/ea', 'US $118.99', 'US $7.95/ea', 'US $24.98/ea',
       'US $64.54/ea', 'US $34.77', 'US $52.99/ea', 'US $24.79/ea',
       'US $269.00', 'US $5.50/ea', 'US $50.73/ea', 'US $26.33/ea',
       'US $46.44/ea', 'US $43.98', 'US $23.97/ea', 'US $44.95/ea',
       'US $32.49/ea', 'US $14.99', 'US $29.26/ea', 'US $19.10/ea',
       'US $19.39/ea', 'US $23.42/ea', 'US $15.31/ea', 'US $174.99',
       'US $50.00/ea', 'US $15.25/ea', 'US $34.43/ea', 'US $42.04/ea',
       'US $10.00/ea', 'US $27.06/ea', 'US $55.99', 'US $69.98/ea',
       'US $17.25/ea', 'US $43.82/ea', 'US $38.00', 'US $29.97/ea',
       'US $52.39/ea', 'US $24.95', 'US $18.75', 'US $72.00/ea',
       'US $18.14/ea', 'US $14.70', 'US $34.93', 'US $28.90',
       'US $128.88', 'US $9.94/ea', 'US $38.89/ea', 'US $74.99',
       'US $19.41/ea', 'US $27.98', 'US $26.15/ea', 'US $26.00',
       'US $40.99', 'US $76.50/ea', 'US $7.99', 'US $78.99/ea',
       'US $40.00', 'US $21.69', 'US $57.63/ea', 'US $27.25',
       'US $23.68/ea', 'US $99.00', 'US $23.00', 'US $34.36/ea',
       'US $44.98', 'US $38.99', 'US $28.60/ea', 'US $45.11',
       'US $50.07/ea', 'US $34.95/ea', 'US $46.94', 'US $17.99/ea',
       'US $29.00/ea', 'US $11.99/ea', 'US $50.00', 'US $20.67/ea',
       'US $21.64/ea', 'US $56.97', 'US $29.89/ea', 'US $13.76/ea',
       'US $9.89', 'US $11.99', 'US $24.74/ea', 'US $71.41/ea',
       'US $80.99', 'US $24.04/ea', 'US $28.68/ea', 'US $34.99',
       'US $27.99', 'US $20.25/ea', 'US $6.99', 'US $32.88/ea',
       'US $55.73/ea', 'US $16.82/ea', 'US $18.35/ea', 'US $4.95/ea',
       'US $19.90', 'US $9.99/ea', 'US $19.95', 'US $16.93/ea',
       'US $11.95/ea', 'US $19.54/ea', 'US $150.00', 'US $44.49/ea',
       'US $14.90/ea', 'US $31.23', 'US $8.98', 'US $37.99/ea',
       'US $18.99', 'US $14.75', 'US $59.32', 'US $285.00', 'US $13.37',
       'US $38.49/ea', 'US $25.98/ea', 'US $9.25', 'US $67.99',
       'US $16.20/ea', 'US $31.41/ea', 'US $13.99/ea', 'US $61.99',
       'US $13.95', 'US $31.95/ea', 'US $49.51/ea', 'US $59.50/ea',
       'US $69.58', 'US $59.23/ea', 'US $35.79/ea', 'US $30.89/ea',
       'US $99.95', 'US $14.94/ea', 'US $29.06/ea', 'US $1.99/ea',
       'US $26.14/ea', 'US $13.75', 'US $16.30/ea', 'US $18.04',
       'US $13.88/ea', 'US $34.09/ea', 'US $55.63', 'US $27.25/ea',
       'US $25.47/ea', 'US $22.95/ea', 'US $18.62/ea', 'US $64.94',
       'US $14.89/ea', 'US $19.24/ea', 'US $18.87', 'US $19.53/ea',
       'US $54.42', 'US $25.99/ea', 'US $24.77/ea', 'US $18.76',
       'US $18.90/ea', 'US $14.49/ea', 'US $26.12/ea', 'US $15.27/ea',
       'US $18.00', 'US $13.99', 'US $19.88/ea', 'US $24.02/ea',
       'US $32.91/ea', 'US $40.63/ea', 'US $26.40/ea', 'US $27.54/ea',
       'US $26.81/ea', 'US $38.76/ea', 'US $58.50', 'US $34.87/ea',
       'US $28.00', 'US $16.99', 'US $17.79/ea', 'US $22.48/ea',
       'US $24.99', 'US $27.50', 'US $45.93/ea', 'US $4.95', 'US $105.95',
       'US $22.53/ea', 'US $39.45/ea', 'US $20.71/ea', 'US $21.00/ea',
       'US $37.00', 'US $23.98/ea', 'US $25.95', 'US $25.56',
       'US $103.99', 'US $72.72/ea', 'US $15.89/ea', 'US $54.90/ea',
       'US $19.98', 'US $7.50', 'US $67.49', 'US $43.30/ea',
       'US $22.97/ea', 'US $66.69/ea', 'US $31.14/ea', 'US $67.98/ea',
       'US $26.95', 'US $10.00', 'US $37.96/ea', 'US $8.00',
       'US $42.90/ea', 'US $134.50', 'US $58.98/ea', 'US $34.33/ea',
       'US $54.51', 'US $30.49/ea', 'US $38.69/ea', 'US $10.35/ea',
       'US $21.90/ea', 'US $22.45', 'US $25.46', 'US $24.00', 'US $55.88',
       'US $100.00', 'US $13.44/ea', 'US $73.99', 'US $34.85',
       'US $47.66/ea', 'US $58.08/ea', 'US $108.99/ea', 'US $299.99',
       'US $53.57', 'US $48.90/ea', 'US $58.69', 'US $9.49/ea',
       'US $18.88/ea', 'US $84.97', 'US $69.89/ea', 'US $125.00',
       'US $275.00', 'US $76.99', 'US $13.50/ea', 'US $88.00/ea',
       'US $15.97', 'US $16.98/ea', 'US $18.95', 'US $27.89', 'US $33.75',
       'US $87.52', 'US $19.73/ea', 'US $17.89', 'US $37.02/ea',
       'US $12.95', 'US $36.94/ea', 'US $39.95/ea', 'US $89.99',
       'US $34.76', 'US $90.00/ea', 'US $59.98/ea', 'US $39.55/ea',
       'US $65.95', 'US $63.25/ea', 'US $50.99', 'US $18.81/ea',
       'US $26.31', 'US $11.94/ea', 'US $55.00', 'US $32.99', 'US $66.95',
       'US $48.93', 'US $27.00', 'US $45.98/ea', 'US $5.65/ea',
       'US $8.34', 'US $28.85/ea', 'US $22.23/ea', 'US $20.30/ea',
       'US $39.82/ea', 'US $55.66/ea', 'US $42.69/ea', 'US $22.36/ea',
       'US $38.00/ea', 'US $31.87/ea', 'US $29.50', 'US $8.99/ea',
       'US $76.34/ea', 'US $37.63/ea', 'US $29.25/ea', 'US $23.89/ea',
       'US $9.39', 'US $32.39', 'US $29.75/ea', 'US $94.99/ea',
       'US $36.68/ea', 'US $7.20/ea', 'US $139.99', 'US $79.95',
       'US $29.60/ea', 'US $38.01/ea', 'US $32.00/ea', 'US $58.62/ea',
       'US $20.93', 'US $85.67', 'US $74.99/ea', 'US $67.14/ea',
       'US $52.38', 'US $22.00/ea', 'US $54.95/ea', 'US $115.22',
       'US $29.66', 'US $11.49', 'US $19.75/ea', 'US $65.55/ea',
       'US $56.99/ea', 'US $28.40/ea', 'US $58.94/ea', 'US $45.98',
       'US $12.15/ea', 'US $13.12/ea', 'US $16.89', 'US $19.48',
       'US $33.86/ea', 'US $24.50/ea', 'US $65.50', 'US $29.79/ea',
       'US $50.22/ea', 'US $31.01', 'US $10.98', 'US $41.34/ea',
       'US $9.90', 'US $21.00', 'US $34.17/ea', 'US $19.30', 'US $70.00',
       'US $40.99/ea', 'US $33.50', 'US $28.18/ea', 'US $23.99/ea',
       'US $43.39', 'US $84.98/ea', 'US $54.00/ea', 'US $20.95',
       'US $16.99/ea', 'US $11.89', 'US $13.75/ea', 'US $35.88/ea',
       'US $92.95/ea', 'US $29.53/ea', 'US $80.00', 'US $64.58',
       'US $23.95', 'US $20.87/ea', 'US $39.00/ea', 'US $22.55',
       'US $124.99', 'US $44.97/ea', 'US $47.69/ea', 'US $24.65',
       'US $50.75', 'US $19.99', 'US $57.85/ea', 'US $30.96',
       'US $14.99/ea'], dtype=object)

cleaning the pricing and currency sections for more clear representation of data. and '/ea' seems like a unit that says ".." $ each unit. so fixing it too

In [ ]:
df['currency'] = df['priceWithCurrency'].str.extract(r'(US \$)')
df['unit'] = df['priceWithCurrency'].str.extract(r'(/ea)')
df.drop(columns=['priceWithCurrency'], inplace=True)

In [107]:
# Drop derived columns (we'll compute in SQL later)
df = df.drop(columns=['update_month', 'update_hour'], errors='ignore')

In [108]:
df.head()

,brand,title,price,available,availableText,sold,lastUpdated,itemLocation,update_date,type,currency,unit
0,Carolina Herrera,good girl by carolina herrera 2.7 oz eau de pa...,43.99,2.0,2 available / 393 sold,393.0,2024-05-23 10:43:50+00:00,"Thomasville, Alabama, United States",2024-05-23,Eau de Parfum,US $,/ea
1,As Shown,parfums de marly delina la rosee eau de parfum...,79.99,5.0,5 available / 40 sold,40.0,2024-05-24 00:15:48+00:00,"New Jersey, Hong Kong",2024-05-24,Eau de Parfum,US $,NaN
2,PRADA,prada paradoxe by prada edp 3.0oz/90ml spray p...,59.99,10.0,More than 10 available / 35 sold,35.0,2024-05-14 20:54:25+00:00,"Orange, New Jersey, United States",2024-05-14,Eau de Parfum,US $,NaN
3,As Show,j'adore parfum d'eau by christian 3.4 oz edp f...,59.99,10.0,More than 10 available / 9 sold,9.0,2024-05-23 01:23:05+00:00,"USA, New Jersey, Hong Kong",2024-05-23,Eau de Parfum,US $,/ea
4,Khadlaj,shiyaaka for men edp spray 100ml (3.4 fl.oz) b...,29.99,10.0,More than 10 available,NaN,NaT,"Little Ferry, New Jersey, United States",NaT,Eau de Parfum,US $,/ea

##**Loading the Dataset**

In [109]:
!pip install google-cloud-bigquery pandas -q

from google.colab import auth
import pandas as pd
from google.cloud import bigquery

# Authenticate
auth.authenticate_user()
# BIGQUERY SETUP

project_id = "perfume-e-commerce-analysis"
dataset_id = "perfume_data"
table_id = "cleaned_perfume_data"

client = bigquery.Client(project=project_id)
table_full_id = f"{project_id}.{dataset_id}.{table_id}"


# DEFINE SCHEMA

job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",
    schema=[
        bigquery.SchemaField("brand", "STRING"),
        bigquery.SchemaField("title", "STRING"),
        bigquery.SchemaField("price", "FLOAT"),
        bigquery.SchemaField("available", "FLOAT"),
        bigquery.SchemaField("availableText", "STRING"),
        bigquery.SchemaField("sold", "FLOAT"),
        bigquery.SchemaField("lastUpdated", "TIMESTAMP"),
        bigquery.SchemaField("itemLocation", "STRING"),
        bigquery.SchemaField("update_date", "DATE"),
        bigquery.SchemaField("type", "STRING"),
    ]
)

# UPLOAD TO BIGQUERY

job = client.load_table_from_dataframe(df, table_full_id, job_config=job_config)

job.result()

print(f"Cleaned data uploaded (month/hour removed) to {table_full_id}")

Cleaned data uploaded (month/hour removed) to perfume-e-commerce-analysis.perfume_data.cleaned_perfume_data